services:
  controlaestoque.database:
    image: mysql:8.0.40
    container_name: controlaestoque.database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
    volumes: 
      - "./.containers/controlaestoque-db:/var/lib/mysql"
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  controlaestoque.api:
    image: ${DOCKER_REGISTRY-}controlaestoqueapi
    container_name: controlaestoque.api
    environment:
      ConnectionStrings__MYSQL_DB_CONNECTION: ${MYSQL_CONNECTION_STRING}
    build:
      context: .
      dockerfile: src/ControlaEstoque.API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on: 
      - controlaestoque.database
    restart: on-failure
